apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: ${ProjectName} 
spec: 
  replicas: 2 
  revisionHistoryLimit: 0 
  selector: 
    matchLabels: 
      k8s-app: ${ProjectName} 
  template: 
    metadata: 
      labels: 
        k8s-app: ${ProjectName} 
      name: ${ProjectName} 
    spec: 
      nodeSelector: 
          agentpool: agentpool 
      restartPolicy: "Never" 
      volumes: 
      - name: dind-storage 
        emptyDir: {} 
      containers: 
      - name: ${ProjectName} 
        image: acr.azurecr.io/${ProjectName}:${build.buildid} 
        imagePullPolicy: IfNotPresent 
        securityContext: 
          privileged: true 
        env: 
          - name: AZP_URL 
            valueFrom: 
              secretKeyRef: 
                name: azpdetails 
                key: azpurl 
          - name: AZP_TOKEN 
            valueFrom: 
              secretKeyRef: 
                name: azpdetails 
                key: azptoken                   
          - name: AZP_POOL 
            value: "Kubernetes Agents" 
          - name: AZP_AGENT_DOWNGRADE_DISABLED 
            value: "true"                       
        volumeMounts: 
        - name: dind-storage 
          mountPath: /var/lib/docker 
      restartPolicy: Always
```
